# Generated by Django 4.0.3 on 2022-04-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraccount__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='_id',
        ),
    ]
