# Generated by Django 4.0.3 on 2022-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_remove_attachment__id_remove_card__id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
