# Generated by Django 4.0.3 on 2022-04-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('color_theme_1', models.CharField(blank=True, max_length=20, null=True)),
                ('color_theme_2', models.CharField(blank=True, max_length=20, null=True)),
                ('color_theme_3', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
