# Generated by Django 4.0.3 on 2022-04-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board__id_alter_board_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
