# Generated by Django 4.0.3 on 2022-04-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='_id',
        ),
    ]
